site_name: Documentation
site_url: https://psalm.dev
repo_url: https://github.com/vimeo/psalm
repo_name: GitHub
site_dir: docs
docs_dir: vendor/vimeo/psalm/docs
theme:
  name: 'material'
  custom_dir: 'theme'
markdown_extensions:
  - codehilite
extra_css:
  - '../assets/css/mkdocs_material_extra.css'
  - 'https://cloud.typography.com/751592/7707372/css/fonts.css'
nav:
  - Documentation Home: README.md
  - Running Psalm:
    - Installation: running_psalm/installation.md
    - Configuration: running_psalm/configuration.md
    - Plugins:
      - Using plugins: running_psalm/plugins/using_plugins.md
      - Authoring plugins: running_psalm/plugins/authoring_plugins.md
      - How Psalm represents types: running_psalm/plugins/plugins_type_system.md
    - Command line usage: running_psalm/command_line_usage.md
    - IDE support: running_psalm/language_server.md
    - Handling errors:
      - Dealing with code issues: running_psalm/dealing_with_code_issues.md
      - Issue Types: running_psalm/issues.md
    - Checking non-PHP files: running_psalm/checking_non_php_files.md
  - Annotating types:
    - Using Type Annotations: annotating_code/typing_in_psalm.md
    - Union Types: annotating_code/type_syntax/union_types.md
    - Atomic Type Reference: annotating_code/type_syntax/atomic_types.md
    - Intersection Types: annotating_code/type_syntax/intersection_types.md
  - Other annotations:
    - Supported Annotations: annotating_code/supported_annotations.md
    - Template Annotations: annotating_code/templated_annotations.md
    - Assert Annotations: annotating_code/adding_assertions.md
  - Manipulating code:
    - Fixing code with Psalter: manipulating_code/fixing.md
    - Refactoring code: manipulating_code/refactoring.md
  - Security analysis:
    - Introduction: security_analysis/index.md
    - Custom taint sources: security_analysis/custom_taint_sources.md
    - Custom taint sinks: security_analysis/custom_taint_sinks.md
    - Avoiding false-positives: security_analysis/avoiding_false_positives.md
